# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package.json .

# Install dependencies
RUN npm install

# Copy all other application files to the working directory
COPY . .

# Expose port 80 to the outside world
EXPOSE 80

# Command to run the application
CMD ["node", "app.js"]
